import { useState, useEffect } from 'react'

import './Popup.css'

const messages = [
  'Hello, world!',
  'Stage Server',
  'Exit',
  'What is the wifi password?',
]

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const minus = () => {
    if (count > 0) setCount(count - 1)
  }

  const add = () => setCount(count + 1)

  const sendMsg = (msg: string) => {
    chrome.tabs.query({ active: true, currentWindow: true }, function(tabs) {
      if (tabs[0].id) {
        chrome.tabs.sendMessage(tabs[0].id, { type: "TALK", msg });
      }
    });
  }

  useEffect(() => {
    chrome.storage.sync.get(['count'], (result) => {
      setCount(result.count || 0)
    })
  }, [])

  useEffect(() => {
    chrome.storage.sync.set({ count })
    chrome.runtime.sendMessage({ type: 'COUNT', count })
  }, [count])

  return (
    <main>
      <h3>Popup Page</h3>
        <div className='d-flex flex-column gap-1'>
          {messages.map((msg, index) => (
            <button key={index} onClick={() => sendMsg(msg)}>{msg}</button>
          ))}
        </div>
      {/* <div className="calc">
        <button onClick={minus} disabled={count <= 0}>
          -
        </button>
        <label>{count}</label>
        <button onClick={add}>+</button>
      </div> */}
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Popup
